/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import configDB.crud_toko; // Menggunakan crud_toko
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frame_toko extends javax.swing.JFrame {

    private crud_toko objekKu; // Membuat objek dari crud_toko
    
    /**
     * Creates new form frame_toko
     */
    public frame_toko() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekKu = new crud_toko();
        objekKu.tampilDataToko(tableToko, "select * from toko");
    }

    // Method untuk membersihkan form
    public void clearForm(){
        txtIdToko.setText(null);
        txtNamaToko.setText(null);
        txtAlamatToko.setText(null);
        txtNoHpToko.setText(null);
        txtRating.setText(null);
        txtProduk.setText(null);
        txtTglDaftar.setText(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdToko = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaToko = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamatToko = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNoHpToko = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTglDaftar = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableToko = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Toko");

        jLabel1.setText("ID Toko");

        jLabel2.setText("Nama Toko");

        jLabel3.setText("Alamat Toko");

        jLabel4.setText("No HP Toko");

        jLabel5.setText("Rating");

        jLabel6.setText("Produk");

        jLabel7.setText("Tgl Daftar User");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        tableToko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tableToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTokoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableToko);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdToko, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtNamaToko)
                            .addComponent(txtAlamatToko)
                            .addComponent(txtNoHpToko)
                            .addComponent(txtRating)
                            .addComponent(txtProduk)
                            .addComponent(txtTglDaftar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCari)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAlamatToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNoHpToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTglDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUpdate)
                            .addComponent(btnHapus)
                            .addComponent(btnClear)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            if (txtIdToko.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID toko belum diisi");
                txtIdToko.requestFocus();
            } else if (txtNamaToko.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Nama toko belum diisi");
                txtNamaToko.requestFocus();
            } // Tambahkan validasi lain jika perlu
            else {
                // Ambil data
                String id_toko = txtIdToko.getText();
                String nama_toko = txtNamaToko.getText();
                String alamat_toko = txtAlamatToko.getText();
                String no_hp_toko = txtNoHpToko.getText();
                String rating = txtRating.getText();
                String produk = txtProduk.getText();
                String tgl_daftar_user = txtTglDaftar.getText();
                
                // Panggil method simpan
                objekKu.simpanToko01(id_toko, nama_toko, alamat_toko, no_hp_toko, rating, produk, tgl_daftar_user);
                
                // Refresh tabel
                objekKu.tampilDataToko(tableToko, "select * from toko");
                
                // Cek jika data duplikat
                if (objekKu.validasi == true){
                    // Tampilkan data yang sudah ada jika ID terdeteksi duplikat
                    txtNamaToko.setText(objekKu.VAR_NAMA_TOKO);
                    txtAlamatToko.setText(objekKu.VAR_ALAMAT_TOKO);
                    txtNoHpToko.setText(objekKu.VAR_NO_HP_TOKO);
                    txtRating.setText(objekKu.VAR_RATING);
                    txtProduk.setText(objekKu.VAR_PRODUK);
                    // txtTglDaftar tidak ada di variabel crud, jadi biarkan
                } else {
                    clearForm(); // Bersihkan form jika berhasil disimpan
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (txtIdToko.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID toko belum diisi");
                txtIdToko.requestFocus();
            } else {
                // Ambil data
                String id_toko = txtIdToko.getText();
                String nama_toko = txtNamaToko.getText();
                String alamat_toko = txtAlamatToko.getText();
                String no_hp_toko = txtNoHpToko.getText();
                String rating = txtRating.getText();
                String produk = txtProduk.getText();
                String tgl_daftar_user = txtTglDaftar.getText();
                
                // Panggil method ubah
                objekKu.ubahToko01(id_toko, nama_toko, alamat_toko, no_hp_toko, rating, produk, tgl_daftar_user);
                
                // Refresh tabel dan bersihkan form
                objekKu.tampilDataToko(tableToko, "select * from toko");
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
             if (txtIdToko.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID toko belum diisi");
                txtIdToko.requestFocus();
            } else {
                objekKu.hapusToko01(txtIdToko.getText());
                clearForm(); // Bersihkan form
                // Refresh tabel
                objekKu.tampilDataToko(tableToko, "select * from toko");
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm(); // Panggil method clearForm
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // Mencari berdasarkan nama toko atau alamat
        String cari = "select * from toko where nama_toko like '%"+txtCari.getText()+"%'"
                + "OR alamat_toko like '%"+txtCari.getText()+"%' ";
        objekKu.tampilDataToko(tableToko, cari);
    }//GEN-LAST:event_txtCariKeyPressed

    private void tableTokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTokoMouseClicked
        // Mengisi form saat data di tabel diklik
        try {
            int baris = tableToko.getSelectedRow();
            txtIdToko.setText(tableToko.getValueAt(baris, 0).toString());
            txtNamaToko.setText(tableToko.getValueAt(baris, 1).toString());
            txtAlamatToko.setText(tableToko.getValueAt(baris, 2).toString());
            txtNoHpToko.setText(tableToko.getValueAt(baris, 3).toString());
            txtRating.setText(tableToko.getValueAt(baris, 4).toString());
            txtProduk.setText(tableToko.getValueAt(baris, 5).toString());
            txtTglDaftar.setText(tableToko.getValueAt(baris, 6).toString());
        } catch (Exception e) {
            //
        }
    }//GEN-LAST:event_tableTokoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_toko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableToko;
    private javax.swing.JTextField txtAlamatToko;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdToko;
    private javax.swing.JTextField txtNamaToko;
    private javax.swing.JTextField txtNoHpToko;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtTglDaftar;
    // End of variables declaration//GEN-END:variables
}