/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import configDB.crud_kurir; // Menggunakan crud_kurir
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frame_kurir extends javax.swing.JFrame {

    private crud_kurir objekKu; // Membuat objek dari crud_kurir
    
    /**
     * Creates new form frame_kurir
     */
    public frame_kurir() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekKu = new crud_kurir();
        objekKu.tampilDataKurir(tableKurir, "select * from kurir");
    }

    // Method untuk membersihkan form
    public void clearForm(){
        txtIdKurir.setText(null);
        txtNamaKurir.setText(null);
        txtKodeKurir.setText(null);
        txtOngkosKirim.setText(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdKurir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaKurir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKodeKurir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOngkosKirim = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKurir = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Kurir");

        jLabel1.setText("ID Kurir");

        jLabel2.setText("Nama Kurir");

        jLabel3.setText("Kode Kurir");

        jLabel4.setText("Ongkos Kirim");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        tableKurir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKurir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKurirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKurir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdKurir, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtNamaKurir)
                            .addComponent(txtKodeKurir)
                            .addComponent(txtOngkosKirim))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCari)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtKodeKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtOngkosKirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUpdate)
                            .addComponent(btnHapus)
                            .addComponent(btnClear)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            if (txtIdKurir.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID kurir belum diisi");
                txtIdKurir.requestFocus();
            } else if (txtNamaKurir.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Nama kurir belum diisi");
                txtNamaKurir.requestFocus();
            } // Tambahkan validasi lain jika perlu
            else {
                // Ambil data dan parse
                String id_kurir = txtIdKurir.getText();
                String nama_kurir = txtNamaKurir.getText();
                String kode_kurir = txtKodeKurir.getText();
                double ongkos_kirim = Double.parseDouble(txtOngkosKirim.getText());
                
                // Panggil method simpan
                objekKu.simpanKurir01(id_kurir, nama_kurir, kode_kurir, ongkos_kirim);
                
                // Refresh tabel
                objekKu.tampilDataKurir(tableKurir, "select * from kurir");
                
                // Cek jika data duplikat
                if (objekKu.validasi == true){
                    // Tampilkan data yang sudah ada jika ID terdeteksi duplikat
                    txtNamaKurir.setText(objekKu.VAR_NAMA_KURIR);
                    txtKodeKurir.setText(objekKu.VAR_KODE_KURIR);
                    txtOngkosKirim.setText(String.valueOf(objekKu.VAR_ONGKOS_KIRIM));
                } else {
                    clearForm(); // Bersihkan form jika berhasil disimpan
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input Ongkos Kirim tidak valid: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (txtIdKurir.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID kurir belum diisi");
                txtIdKurir.requestFocus();
            } else {
                // Ambil data dan parse
                String id_kurir = txtIdKurir.getText();
                String nama_kurir = txtNamaKurir.getText();
                String kode_kurir = txtKodeKurir.getText();
                double ongkos_kirim = Double.parseDouble(txtOngkosKirim.getText());
                
                // Panggil method ubah
                objekKu.ubahKurir01(id_kurir, nama_kurir, kode_kurir, ongkos_kirim);
                
                // Refresh tabel dan bersihkan form
                objekKu.tampilDataKurir(tableKurir, "select * from kurir");
                clearForm();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input Ongkos Kirim tidak valid: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
             if (txtIdKurir.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID kurir belum diisi");
                txtIdKurir.requestFocus();
            } else {
                objekKu.hapusKurir01(txtIdKurir.getText());
                clearForm(); // Bersihkan form
                // Refresh tabel
                objekKu.tampilDataKurir(tableKurir, "select * from kurir");
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm(); // Panggil method clearForm
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // Mencari berdasarkan nama kurir atau kode kurir
        String cari = "select * from kurir where nama_kurir like '%"+txtCari.getText()+"%'"
                + "OR kode_kurir like '%"+txtCari.getText()+"%' ";
        objekKu.tampilDataKurir(tableKurir, cari);
    }//GEN-LAST:event_txtCariKeyPressed

    private void tableKurirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKurirMouseClicked
        // Mengisi form saat data di tabel diklik
        try {
            int baris = tableKurir.getSelectedRow();
            txtIdKurir.setText(tableKurir.getValueAt(baris, 0).toString());
            txtNamaKurir.setText(tableKurir.getValueAt(baris, 1).toString());
            txtKodeKurir.setText(tableKurir.getValueAt(baris, 2).toString());
            txtOngkosKirim.setText(tableKurir.getValueAt(baris, 3).toString());
        } catch (Exception e) {
            //
        }
    }//GEN-LAST:event_tableKurirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_kurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_kurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_kurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_kurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_kurir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKurir;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdKurir;
    private javax.swing.JTextField txtKodeKurir;
    private javax.swing.JTextField txtNamaKurir;
    private javax.swing.JTextField txtOngkosKirim;
    // End of variables declaration//GEN-END:variables
}