/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

// Impor semua kelas CRUD yang diperlukan
import configDB.crud_transaksi;
import configDB.crud_toko;
import configDB.crud_produk;
import configDB.crud_kurir;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frame_transaksi extends javax.swing.JFrame {

    private crud_transaksi objekKu;
    private crud_toko objekToko;
    private crud_produk objekProduk;
    private crud_kurir objekKurir;
    
    /**
     * Creates new form frame_transaksi
     */
    public frame_transaksi() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Inisialisasi semua objek CRUD
        objekKu = new crud_transaksi();
        objekToko = new crud_toko();
        objekProduk = new crud_produk();
        objekKurir = new crud_kurir();
        
        // Isi tabel saat form dibuka
        objekKu.tampilDataTransaksi(tableTransaksi, "select * from transaksi");
        
        // Isi semua ComboBox
        isiComboBoxToko();
        isiComboBoxProduk();
        isiComboBoxKurir();
        
        // Atur field yang dihitung ke 0
        txtHarga.setText("0");
        txtTotalHarga.setText("0");
        txtOngkosKirim.setText("0");
        txtJlhTotal.setText("0");
    }
    
    // Method untuk mengisi ComboBox Toko
    public void isiComboBoxToko(){
        ArrayList<String> list = objekToko.getNamaTokoList();
        cmbNamaToko.removeAllItems();
        cmbNamaToko.addItem("Pilih Toko");
        for(String nama : list){
            cmbNamaToko.addItem(nama);
        }
    }
    
    // Method untuk mengisi ComboBox Produk
    public void isiComboBoxProduk(){
        ArrayList<String> list = objekProduk.getNamaProdukList();
        cmbNamaProduk.removeAllItems();
        cmbNamaProduk.addItem("Pilih Produk");
        for(String nama : list){
            cmbNamaProduk.addItem(nama);
        }
    }
    
    // Method untuk mengisi ComboBox Kurir
    public void isiComboBoxKurir(){
        ArrayList<String> list = objekKurir.getKodeKurirList();
        cmbKodeKurir.removeAllItems();
        cmbKodeKurir.addItem("Pilih Kurir");
        for(String kode : list){
            cmbKodeKurir.addItem(kode);
        }
    }
    
    // Method untuk membersihkan form
    public void clearForm(){
        txtIdTransaksi.setText(null);
        txtTglBeli.setText(null);
        txtNamaUser.setText(null);
        cmbNamaToko.setSelectedIndex(0);
        cmbNamaProduk.setSelectedIndex(0);
        txtHarga.setText("0");
        txtJlhProduk.setText(null);
        txtTotalHarga.setText("0");
        cmbKodeKurir.setSelectedIndex(0);
        txtOngkosKirim.setText("0");
        txtJlhTotal.setText("0");
    }
    
    // Method untuk menghitung Total Harga (Produk * Jumlah)
    private void hitungTotalHarga() {
        try {
            double harga = Double.parseDouble(txtHarga.getText());
            int jlh = 0;
            if (!txtJlhProduk.getText().isEmpty()) {
                jlh = Integer.parseInt(txtJlhProduk.getText());
            }
            double total = harga * jlh;
            txtTotalHarga.setText(String.valueOf(total));
        } catch (NumberFormatException e) {
            txtTotalHarga.setText("0");
        }
        // Panggil juga hitung jumlah total agar update
        hitungJumlahTotal();
    }

    // Method untuk menghitung Jumlah Total (Total Harga + Ongkir)
    private void hitungJumlahTotal() {
        try {
            double totalHarga = Double.parseDouble(txtTotalHarga.getText());
            double ongkir = Double.parseDouble(txtOngkosKirim.getText());
            double jlhTotal = totalHarga + ongkir;
            txtJlhTotal.setText(String.valueOf(jlhTotal));
        } catch (NumberFormatException e) {
            txtJlhTotal.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdTransaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTglBeli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbNamaToko = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbNamaProduk = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtJlhProduk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbKodeKurir = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtOngkosKirim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtJlhTotal = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Transaksi");

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("Tgl Beli");

        jLabel3.setText("Nama User");

        jLabel4.setText("Nama Toko");

        cmbNamaToko.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Nama Produk");

        cmbNamaProduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNamaProdukActionPerformed(evt);
            }
        });

        jLabel6.setText("Harga");

        txtHarga.setEditable(false);

        jLabel7.setText("Jlh Produk");

        txtJlhProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJlhProdukKeyReleased(evt);
            }
        });

        jLabel8.setText("Total Harga");

        txtTotalHarga.setEditable(false);

        jLabel9.setText("Kode Kurir");

        cmbKodeKurir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKodeKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKodeKurirActionPerformed(evt);
            }
        });

        jLabel10.setText("Ongkos Kirim");

        txtOngkosKirim.setEditable(false);

        jLabel11.setText("Jlh Total");

        txtJlhTotal.setEditable(false);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtTglBeli)
                            .addComponent(txtNamaUser)
                            .addComponent(cmbNamaToko, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbNamaProduk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHarga)
                            .addComponent(txtJlhProduk)
                            .addComponent(txtTotalHarga)
                            .addComponent(cmbKodeKurir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOngkosKirim)
                            .addComponent(txtJlhTotal))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCari)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTglBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbNamaToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtJlhProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbKodeKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtOngkosKirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtJlhTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUpdate)
                            .addComponent(btnHapus)
                            .addComponent(btnClear)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            if (txtIdTransaksi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID transaksi belum diisi");
                txtIdTransaksi.requestFocus();
            } else if (cmbNamaToko.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null,"Nama toko belum dipilih");
                cmbNamaToko.requestFocus();
            } else if (cmbNamaProduk.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null,"Nama produk belum dipilih");
                cmbNamaProduk.requestFocus();
            } else if (cmbKodeKurir.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null,"Kode kurir belum dipilih");
                cmbKodeKurir.requestFocus();
            } else if (txtJlhProduk.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Jumlah produk belum diisi");
                txtJlhProduk.requestFocus();
            } else {
                // Ambil data dan parse
                String id_transaksi = txtIdTransaksi.getText();
                String tgl_beli = txtTglBeli.getText();
                String nama_user = txtNamaUser.getText();
                String nama_toko = cmbNamaToko.getSelectedItem().toString();
                String nama_produk = cmbNamaProduk.getSelectedItem().toString();
                double harga = Double.parseDouble(txtHarga.getText());
                int jlh_produk = Integer.parseInt(txtJlhProduk.getText());
                double total_harga = Double.parseDouble(txtTotalHarga.getText());
                String kode_kurir = cmbKodeKurir.getSelectedItem().toString();
                double ongkos_kirim = Double.parseDouble(txtOngkosKirim.getText());
                double jlh_total = Double.parseDouble(txtJlhTotal.getText());
                
                // Panggil method simpan
                objekKu.simpanTransaksi01(id_transaksi, tgl_beli, nama_user, nama_toko, nama_produk, harga, jlh_produk, total_harga, kode_kurir, ongkos_kirim, jlh_total);
                
                // Refresh tabel
                objekKu.tampilDataTransaksi(tableTransaksi, "select * from transaksi");
                
                // Cek jika data duplikat
                if (objekKu.validasi == true){
                    // Tampilkan data yang sudah ada jika ID terdeteksi duplikat
                    txtTglBeli.setText(objekKu.VAR_NAMA_USER); // Perlu disesuaikan dengan variabel di crud_transaksi
                    txtNamaUser.setText(objekKu.VAR_NAMA_USER);
                    cmbNamaToko.setSelectedItem(objekKu.VAR_NAMA_TOKO);
                    cmbNamaProduk.setSelectedItem(objekKu.VAR_NAMA_PRODUK);
                    txtHarga.setText(String.valueOf(objekKu.VAR_HARGA));
                    txtJlhProduk.setText(String.valueOf(objekKu.VAR_JLH_PRODUK));
                    txtTotalHarga.setText(String.valueOf(objekKu.VAR_TOTAL_HARGA));
                    cmbKodeKurir.setSelectedItem(objekKu.VAR_KODE_KURIR);
                    txtOngkosKirim.setText(String.valueOf(objekKu.VAR_ONGKOS_KIRIM));
                    txtJlhTotal.setText(String.valueOf(objekKu.VAR_JLH_TOTAL));
                } else {
                    clearForm(); // Bersihkan form jika berhasil disimpan
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input Angka tidak valid: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (txtIdTransaksi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID transaksi belum diisi");
                txtIdTransaksi.requestFocus();
            } else {
                // Ambil data dan parse
                String id_transaksi = txtIdTransaksi.getText();
                String tgl_beli = txtTglBeli.getText();
                String nama_user = txtNamaUser.getText();
                String nama_toko = cmbNamaToko.getSelectedItem().toString();
                String nama_produk = cmbNamaProduk.getSelectedItem().toString();
                double harga = Double.parseDouble(txtHarga.getText());
                int jlh_produk = Integer.parseInt(txtJlhProduk.getText());
                double total_harga = Double.parseDouble(txtTotalHarga.getText());
                String kode_kurir = cmbKodeKurir.getSelectedItem().toString();
                double ongkos_kirim = Double.parseDouble(txtOngkosKirim.getText());
                double jlh_total = Double.parseDouble(txtJlhTotal.getText());
                
                // Panggil method ubah
                objekKu.ubahTransaksi01(id_transaksi, tgl_beli, nama_user, nama_toko, nama_produk, harga, jlh_produk, total_harga, kode_kurir, ongkos_kirim, jlh_total);
                
                // Refresh tabel dan bersihkan form
                objekKu.tampilDataTransaksi(tableTransaksi, "select * from transaksi");
                clearForm();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input Angka tidak valid: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
             if (txtIdTransaksi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"ID transaksi belum diisi");
                txtIdTransaksi.requestFocus();
            } else {
                objekKu.hapusTransaksi01(txtIdTransaksi.getText());
                clearForm(); // Bersihkan form
                // Refresh tabel
                objekKu.tampilDataTransaksi(tableTransaksi, "select * from transaksi");
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm(); // Panggil method clearForm
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // Mencari berdasarkan nama user atau nama produk
        String cari = "select * from transaksi where nama_user like '%"+txtCari.getText()+"%'"
                + "OR nama_produk like '%"+txtCari.getText()+"%' ";
        objekKu.tampilDataTransaksi(tableTransaksi, cari);
    }//GEN-LAST:event_txtCariKeyPressed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        // Mengisi form saat data di tabel diklik
        try {
            int baris = tableTransaksi.getSelectedRow();
            txtIdTransaksi.setText(tableTransaksi.getValueAt(baris, 0).toString());
            txtTglBeli.setText(tableTransaksi.getValueAt(baris, 1).toString());
            txtNamaUser.setText(tableTransaksi.getValueAt(baris, 2).toString());
            cmbNamaToko.setSelectedItem(tableTransaksi.getValueAt(baris, 3).toString());
            cmbNamaProduk.setSelectedItem(tableTransaksi.getValueAt(baris, 4).toString());
            txtHarga.setText(tableTransaksi.getValueAt(baris, 5).toString());
            txtJlhProduk.setText(tableTransaksi.getValueAt(baris, 6).toString());
            txtTotalHarga.setText(tableTransaksi.getValueAt(baris, 7).toString());
            cmbKodeKurir.setSelectedItem(tableTransaksi.getValueAt(baris, 8).toString());
            txtOngkosKirim.setText(tableTransaksi.getValueAt(baris, 9).toString());
            txtJlhTotal.setText(tableTransaksi.getValueAt(baris, 10).toString());
        } catch (Exception e) {
            //
        }
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void cmbNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNamaProdukActionPerformed
        // Saat produk dipilih, ambil harganya
        try {
            if (cmbNamaProduk.getSelectedIndex() > 0) { // Pastikan bukan placeholder "Pilih Produk"
                String namaProduk = cmbNamaProduk.getSelectedItem().toString();
                double harga = objekProduk.getHargaByNama(namaProduk);
                txtHarga.setText(String.valueOf(harga));
            } else {
                txtHarga.setText("0");
            }
        } catch (Exception e) {
            txtHarga.setText("0");
        }
        // Hitung ulang total
        hitungTotalHarga();
    }//GEN-LAST:event_cmbNamaProdukActionPerformed

    private void cmbKodeKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKodeKurirActionPerformed
        // Saat kurir dipilih, ambil ongkirnya
        try {
            if (cmbKodeKurir.getSelectedIndex() > 0) { // Pastikan bukan placeholder "Pilih Kurir"
                String kodeKurir = cmbKodeKurir.getSelectedItem().toString();
                double ongkir = objekKurir.getOngkirByKode(kodeKurir);
                txtOngkosKirim.setText(String.valueOf(ongkir));
            } else {
                txtOngkosKirim.setText("0");
            }
        } catch (Exception e) {
            txtOngkosKirim.setText("0");
        }
        // Hitung ulang jumlah total
        hitungJumlahTotal();
    }//GEN-LAST:event_cmbKodeKurirActionPerformed

    private void txtJlhProdukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJlhProdukKeyReleased
        // Saat jumlah produk diubah, hitung ulang total harga
        hitungTotalHarga();
    }//GEN-LAST:event_txtJlhProdukKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbKodeKurir;
    private javax.swing.JComboBox<String> cmbNamaProduk;
    private javax.swing.JComboBox<String> cmbNamaToko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtJlhProduk;
    private javax.swing.JTextField txtJlhTotal;
    private javax.swing.JTextField txtNamaUser;
    private javax.swing.JTextField txtOngkosKirim;
    private javax.swing.JTextField txtTglBeli;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}